### ISSUE TITLE
Meeting Minutes for Week 2

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/test-creation#27]
**Sprint Planning - 2024/05/06 Week 2**

- We can start from user story for every week sprint
- We have define N user story, further break down user story into functions/work
- There are 3 layers of project planning 
- Layer 0: (highest): the overview of the products’ functionalities and stories
- Layer 1 (higher): Epic, mainly linked to the user story(s) every week
- Layer 2 (lower): Task, daily tasks
- User Story 1: Proposal
- Task: Finish the proposal
  - [x] Review the proposal by the team
  - [x] Check with Simon on 1) the necessity of reproducible tool and 2) what does he mean by “proposed figures”, 3) if we should include the cost into Proposal https://github.com/UBC-MDS/test-creation/issues/20
  - [x] Polish reference links https://github.com/UBC-MDS/test-creation/issues/23
  - [x] Add the data example screencap into Session 3.3.1 https://github.com/UBC-MDS/test-creation/issues/23
  - [x] Add the budget for the cost for development https://github.com/UBC-MDS/test-creation/issues/21
- User Story 2: User can get ML test completion score
  - [ ] #24
- User Story 3: Researcher/Leader get the checklist to push the best practice for ML test
  - [ ] #25 
- Task: Estimate the cost for development
  - e.g. API cost
  - [x] Check with Simon 1) how to estimate the cost for development, 2) if Simon can lend his GPT4 and API key for our work in May 2024 https://github.com/UBC-MDS/test-creation/issues/20
  - [x] Track the API usage and cost for Week 2 https://github.com/UBC-MDS/test-creation/issues/14
Task: weekly meeting with Tiffany
  - [x] confirm the meeting time with Tiffany https://github.com/UBC-MDS/test-creation/issues/22

**Comment by tonyshumlh** [comment]
**Mentor Meeting 2024/05/09**
- [ ] Use bib/common reference addition method in the checklist YAML
- [ ] Replace "Data Presence...." by "Topic: Data Presence...." in checklist YAML
```
"Data Presence" itself has no meaning, we should keep the meaningful thing as properties/keys, e.g. "Topic" and ensure consistent key 
```
- [ ] Make ppt 1) group name & date; 2) overview (content); 3) user stories; 4) checklist structure; 5) system graph; 6) prompt & POC; 
- Success metrics: mention whether we can fulfill all user stories 
- Confirm system structure, user stories with Tiffany in the first meeting
- Move some words from proposal into Figure Caption
- Take reference of Neotoma Explorer Scenario (Simon paper) for user stories

**Comment by tonyshumlh** [comment]
Partner Meeting 05/09
- [ ] (Good to have) Can the LLM model be trained to build up knowledge when users use our application to persist states? e.g. StoryBird.ai. At least some discussion in the final report.
```
Such that the program has the context without starting fresh every time
```
- Structure the response based on the checklist item topics
-

**Comment by JohnShiuMK** [comment]
**Partner Meeting Minutes - May 9, 2024**

**Key Points Discussed:**
1. Test Cases on Data Quality and Handling: need to ensure the implementation of test cases for data quality and handling e.g. train-test split
  - relevant work: a paper (https://arxiv.org/pdf/2310.01402) by a professor from the University of Toronto
  - Tiffany will invite the professor to attend our final presentation.

2. Enhancing the Application:
  - Proposed the use of LLM to refine and adjust the "explanation" in our checklist for better user understanding
  - Suggested that the application should have the capability to build and retain knowledge over time, similar to how [StoryBird.ai](http://storybird.ai/) operates. This would allow the application to maintain some context and not start from scratch with each use.
    - Agreed that this feature is nice-to-have and should at least be discussed in the final report.
  - Discussed the potential for the application to tailor responses based on user-specific topic, which could be one of the topics in our checklist.

3. Meeting Coordination:
  - Agreed to confirm and align on the meeting time one day before the next meeting

**Comment by tonyshumlh** [comment]
**Sprint Planning - 2024/05/13 Week 3**
-
